## custom app properties
#info:
#  app:
#    name: ${spring.application.name}
#    desc: ${spring.application.desc}
#    version: ${spring.application.version}
#    author: Voivod
#    build-timestamp: #{maven.build.timestamp}
#    profiles:
#      active: ${spring.profiles.active}

# expose actuator metrics endpoints
management:
  endpoints:
    web:
      exposure:
        include:
          - 'health'
          - 'info'
        info:
          env:
            enabled: true

## jms properties
##spring.jms.pub-sub-domain=false
##activemq.broker-url=tcp://localhost:61616
##emp.jms.topic=EmpTopic
##emp.jms.queue=EmpQueue
