openApi: 3.0.3

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: <<ENTER DB URL>>
    username: <<USER>>
    password: <<PASSWORD>>
  profiles:
    active: #{spring.profiles.active}
  application:
    name: #{project.name}
    version: #{project.version}
    desc: #{project.description}
  jms:
    pub-sub-domain: false

# custom app properties
info:
  app:
    name: ${spring.application.name}
    desc: ${spring.application.desc}
    version: ${spring.application.version}
    author: BabinKuk
    build-timestamp: #{maven.build.timestamp}
    profiles:
      active: ${spring.profiles.active}

# expose actuator metrics endpoints
management:
  endpoints:
    web:
      exposure:
        include:
          - 'health'
#          - 'info'
        info:
          env:
            enabled: true

# jms properties
activemq:
  broker-url: tcp://localhost:61616
emp:
  jms:
    topic: EmpTopic
    queue: EmpQueue
